//  Copyright (c) 2017, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: rest-intro
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2017-09-19
:page-guide-category: microprofile
:page-essential: true
:page-essential-order: 1
:page-description: Learn how to create a REST service with JAX-RS, JSON-P, and Open Liberty.
:guide-author: Open Liberty
:page-tags: ['MicroProfile', 'Java EE']
:page-related-guides: ['rest-client-java', 'rest-client-angularjs']
:page-permalink: /guides/{projectid}
:repo-description: Visit the https://openliberty.io/guides/{projectid}.html[website] for the rendered version of the guide.
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= RESTfulなwebサービスの作成

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

OpenLibertyでRESTサービスを作る方法について学びます。

== このガイドで学ぶこと

このガイドでは、JAX-RSとJSON-Pを使って簡単なRESTサービスを構築し、テストする方法を学びます。
このサービスは `\http://localhost:9080/LibertyProject/System/properties` への `GET` リクエストに応答して、JVMのシステムプロパティを表示するものです。 

このサービスは、`GET`リクエストに対して、システムプロパティの内容をJSON形式で 応答します。
各プロパティは、次のように、JSONオブジェクトのフィールドで表示されます。

[source,json,role="no_copy"]
----
{
  "os.name":"Mac",
  "java.version": "1.8"
}
----

新しいRESTアプリケーションを作成するときには、きちんとAPIの設計をすることが重要です。 JAX-RS APIは、JSON-RPC、またはXML-RPC APIを作成するためにも使用できますが、それはRESTfulなサービスではありません。良いRESTfulサービスは、サービスによって公開されているリソースを、作成、読み取り、更新、削除できるように設計します。このガイドの例では、システムプロパティが、公開されているリソースとなります。

サービスは `/System/properties` というパスへ`GET`リクエストが送られると、 `200 OK` と共に、JVMのすべてのシステムプロパティを返します。

[role="command"]
include::{common-includes}/gitclone.adoc[]

include::{common-includes}/trywhatyoubuild-beg.adoc[]

下記のURLにアクセスしてサービスを見てみましょう。
http://localhost:9080/LibertyProject/System/properties[^] URL. 

[role=command]
include::{common-includes}/trywhatyoubuild-end.adoc[]

== JAX-RSアプリケーションを作成してみよう

まず　`start` ディレクトリに移動します。

JAX-RSには、REST APIを作成するための2つの重要な概念があります。１つめの概念は、リソース自体で、クラスとしてモデル化されています。２つ目の概念はJAX-RSアプリケーションです。JAX-RSアプリケーションが、公開されたすべてのリソースを共通のパスの下にグループ化します。 JAX-RSアプリケーションは、すべてのリソースのラッパー（操作を扱いやすくする仕組み）として考えることができます。普通は、１つのJAX-RSアプリケーションを作るのが一般的ですが、複数のJAX-RSアプリケーションを作成することも可能です。

[role="code_command hotspot",subs="quotes"]
----
#Create the `SystemApplication` class.#
`src/main/java/io/openliberty/guides/rest/SystemApplication.java`
----

[hotspot=7-9]　`SystemApplication` クラスは、 `Application` クラスを拡張しています。この`Application` クラスは、すWARファイルの中のすべてのJAX-RSのリソースクラスを、このJAX-RSのアプリケーションと関連付けます。この関連付けにより、リソースが [hotspot=7-9]　`SystemApplication` 内の共通のパスの元で利用できるようになります。 [hotspot=6]　`@ApplicationPath` アノテーションに指定された値が、JAX-RSアプリケーションがリクエストを受け付けるパスとなります。
 
SystemApplication.java
[source,java,linenums,role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/rest/SystemApplication.java[tags=**;!comment]
----

== JAX-RSのリソースを作成してみよう

JAX-RSでは、１つのクラスは、１つのリソースか、または同じタイプのリソースのグループでなければなりません。このアプリケーションでは、リソースはシステムプロパティ、またはシステムプロパティのセットです。 1つのクラスで複数の異なるリソースを処理することも出来ますが、リソースの種類を明確に区別することで長期的な保守性が向上します。

[role="code_command hotspot", subs="quotes"]
----
#Create the `PropertiesResource` class.#
`src/main/java/io/openliberty/guides/rest/PropertiesResource.java`
----

このリソースクラスにはかなりの量のコードが含まれているので、少しずつ見ていきます。

[hotspot=11 file=0] `@ Path`　アノテーションは、このリソースが `properties` パスに応答することを示しています。
[hotspot=7-9 file=1]`SystemApplication` クラスの [hotspot=6 file=1]`@ApplicationPath` アノテーションと一緒に合わせると、
このクラスの[hotspot = 11 file = 0] `@Path`アノテーションは、リソースを`System/properties` のパスで利用できるようにします。

JAX-RSは、URLのHTTPメソッドを、クラスのメソッドにマッピングします。呼び出すメソッドは、メソッドに指定されているアノテーションによって決まります。このアプリケーションでは `System/properties` パスへのHTTP GETリクエストはシステムプロパティを返します。

メソッドの上の[hotspot=14 file=0] `@ GET` アノテーションは、このメソッドがHTTPの `GET` に対して呼び出されることを示しています
[hotspot=15 file=0] `@Produces` アノテーションは返されるコンテンツのフォーマットを示します。
[hotspot=15 file=0] `@Produces` アノテーションの値はHTTPの `Content-Type` レスポンスヘッダで指定されます。
このアプリケーションでは、JSON構造体が返されます。 JSONに望ましい `Content-Type` レスポンスは `String` ではなく `application/json` です。リテラルコードで表すと `application/json`は、`MediaType.APPLICATION_JSON`　となります。MediaType.APPLICATION_JSONなどのリテラルコードを使用するのは、スペルミスの場合にコンパイルエラーが発生するので、それを防ぐためです。

JAX-RSはJSON構造体を作るため、いくつかの方法をサポートしています。 JAX-RS仕様は、JSON-Processing（JSON-P）とJAX-Bを義務付けています。ほとんどのJAX-RS実装は、Java POJO（Plain Old Java Object=昔からある普通のJavaオブジェクト）からJSONへの変換もサポートしています。これを使ってJSONオブジェクトを返すかわりに、Propertiesオブジェクトを返すことができます。この変換はより単純な実装を可能にしますが、POJOからJSONへの変換は標準的ではないため、コードの移植性が制限されていました。仕様のこのギャップは、JSON-Bを含めることでJava EE 8で修正されています。

The method body does the following actions:

. まず  `Json` クラスを使用して、 [hotspot=18 file=0]`JsonObjectBuilder` オブジェクトを作ります。次に [hotspot=18 file=0]`JsonObjectBuilder` を使って、`JsonObject` とその値を入力していきます。
.  `System` クラスの [hotspot=20 file=0]`getProperties` メソッドを呼び出して、すべてのシステムプロパティを含む `Properties` オブジェクトを取得します。
.  `Properties` オブジェクトの [hotspot=21 file=0]`entrySet` メソッドを呼び出して、すべてのプロパティーの `Set` を取得します。
. 　[hotspot=22 file=0]`stream` メソッドを呼んで `Set` を `Stream` (Java SE 8で新規追加された機能)に変換します。 Stream　はリストの中のエントリーを一つずつ見ていく作業を簡単にしてくれます。
. Calls the [hotspot=23-24 file=0]`forEach` method on the `Stream` passing in a function that will be invoked for each
entry in the `Stream`. The function passed in will call the [hotspot=23-24 file=0]`add` method on the [hotspot=18 file=0]`JsonObjectBuilder`
for every entry in the stream. The key and value for the `JsonObject` will be obtained by calling
the [hotspot=23 file=0]`getKey` and [hotspot=24 file=0]`getValue` methods on the `Map.Entry` objects in the stream.
. Returns the `JsonObject` by calling the [hotspot=26 file=0]`build` method on the [hotspot=18 file=0]`JsonObjectBuilder`.

PropertiesResource.java
[source,java,linenums,role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/rest/PropertiesResource.java[tags=**;!comment]
----

SystemApplication.java
[source,java,linenums,role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/rest/SystemApplication.java[tags=**;!comment]
----

== Configuring the server

To get the service running, the Liberty server needs to be correctly configured.

[role="code_command hotspot", subs="quotes"]
----
#Create the server configuration file.#
`src/main/liberty/config/server.xml`
----

server.xml
[source,xml,linenums,role="code_column"]
----
include::finish/src/main/liberty/config/server.xml[]
----

The configuration does the following actions:

. Configures the server to support both JAX-RS and JSON-P. This is specified in the [hotspot=3-6 file=0]`featureManager` element.
. Configures the server to pick up the HTTP port numbers from variables, which are then specified in
the Maven [hotspot file=1]`pom.xml` file. This is specified in the [hotspot=8-9 file=0]`<httpEndpoint/>` element. Variables use the syntax `${variableName}`.
. Configures the server to run the produced Web application on a context root specified in the Maven
[hotspot file=1]`pom.xml` file. This is specified in the [hotspot=11 file=0]`<webApplication/>` element.

pom.xml
[source,xml,linenums,role="code_column"]
----
include::finish/pom.xml[tags=**]
----

The variables being used in the [hotspot file=0]`server.xml` file are provided by the [hotspot=148-152 file=1]`<bootstrapProperties/>` section
of the Maven [hotspot file=1]`pom.xml`.

[role="command"]
include::{common-includes}/mvnbuild.adoc[]

Check out the service you created at the
http://localhost:9080/LibertyProject/System/properties[^] URL. 

When you are done checking out the services, stop the Open Liberty server by running the following command:
[role="command"]
```
mvn liberty:stop-server
```

== Testing the service

You could test this service manually by starting a server and pointing a web browser at the
http://localhost:9080/LibertyProject/System/properties[^] URL. Automated tests are a much better
approach because they will trigger a failure if a change introduces a bug. JUnit and the JAX-RS Client
API provide a very simple environment to test the application.

You can write tests for the individual units of code outside of a running application server, or they
can be written to call the application server directly. In this example, you will create a test that
does the latter.

[role="code_command hotspot", subs="quotes"]
----
#Create the `EndpointTest` class.#
`src/test/java/it/io/openliberty/guides/rest/EndpointTest.java`
----

EndpointTest.java
[source,java,linenums,role="code_column"]
----
include::finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java[tags=**;!comment]
----

This test class has more lines of code than the resource implementation. This situation is common.
The test method is indicated with the [hotspot=16 file=0]`@Test` annotation.

pom.xml
[source,xml,linenums,role="code_column"]
----
include::finish/pom.xml[tags=**]
----

The test code needs to know some information about the application in order to make requests. The server
port and the application context root are key, and are dictated by the server configuration. While this
information can be hardcoded, it is better to specify it in a single place like the Maven [hotspot file=1]`pom.xml`
file. Refer to the [hotspot file=1]`pom.xml` file to see how the application information such as the [hotspot=22 file=1]`<app.name/>`, [hotspot=23 file=1]`<testServerHttpPort/>` and [hotspot=24 file=1]`<testServerHttpsPort/>` elements are provided in the file.

These Maven properties are then passed to the Java test program as the [hotspot=187-191 file=1]`<systemPropertyVariables/>` element in
the [hotspot file=1]`pom.xml` file.

Getting the values to create a representation of the URL is simple. The test class uses the [hotspot=18-19 file=0]`getProperty` method
to get the application details.

The JAX-RS client can be used to make the REST call and convert the payload to and from a JSON-P
representation. To get the JAX-RS client to do the conversion, the client needs to have the `JsrJsonpProvider`
class registered with it by calling the [hotspot=23 file=0]`register` method and providing the `Class` object for the
`JsrJsonpProvider` class.

To call the JAX-RS service using the JAX-RS client, you first create a `WebTarget` object by calling
the [hotspot=25 file=0]`target` method providing the URL. To cause the HTTP request to occur first the [hotspot=26 file=0]`request` method
on `WebTarget` and then the [hotspot=26 file=0]`get` method on the returned object need to be called. The [hotspot=26 file=0]`get` method
call is a synchronous call that blocks until a response is received. This call returns a [hotspot=26 file=0]`Response`
object, which can be interrogated to determine whether the request was successful.

The first thing to check is that a `200` response was received. The JUnit [hotspot=28-29 file=0]`assertEquals` method can
be used for this. The first parameter is the error message that indicates why the test failed. The
second parameter is the expected response code, and the third is the actual response code. It is
important to associate the expected response code with the second parameter and the actual response
with the third parameter. Otherwise, the error messages from JUnit will claim that the actual response
is the expected one, which can cause confusion.

Check the response body to ensure it returned the right information. Since the client and the server
are running on the same machine, it is reasonable to expect that the system properties for the local
and remote JVM would be the same. In this case, an assertion is made that the `os.name` system property
for both JVMs is the same. You could write additional assertions [hotspot=33-35 file=0]`assertEquals` to check for more values.

=== Running the tests

If the server is still running from the previous steps, stop it using the Maven `liberty:stop-server` goal from command line in the start directory:
[role="command"]
```
mvn liberty:stop-server
```

To rebuild, run the tests, and see that the test passes, run the Maven `install` command: 

[role='command']
```
mvn install
```

The Maven
build takes a little longer than before the test existed, but expect to see the following information
in the output:

[source,role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.rest.EndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.884 sec - in it.io.openliberty.guides.rest.EndpointTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

To see whether the tests detect a failure, add an assertion that you know fails, or change the existing
assertion to a constant value that doesn't match the `os.name` system property.

== Great work! You're done!

You developed a REST service in Open Liberty by using JAX-RS and JSON-P.

== Related Links

Learn more about MicroProfile.

https://microprofile.io/[See the MicroProfile specs^]

https://openliberty.io/docs/ref/microprofile[View the MicroProfile API^]


include::{common-includes}/attribution.adoc[subs="attributes"]
